import React from 'react'
import { ArrowLeft, ChevronRight } from 'lucide-react'

const money = (value) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', notation: value > 9999999 ? 'compact' : 'standard', maximumFractionDigits: 1 }).format(value || 0)
const crore = (value) => `Rs ${((value || 0) / 10000000).toFixed(1)} Cr`
const pretty = (value) => String(value || '').replaceAll('_', ' ')
const riskTone = (score) => score > .6 ? 'high' : score >= .4 ? 'medium' : 'low'

function RiskBar({ score }) { const tone = riskTone(score); return <div className="flex min-w-28 items-center gap-2"><div className="h-2 flex-1 rounded-full bg-divider"><div className={`h-2 rounded-full ${tone === 'low' ? 'bg-forest' : tone === 'medium' ? 'bg-amber' : 'bg-brick'}`} style={{ width: `${Math.round(score * 100)}%` }} /></div><span className={`text-xs font-bold ${tone === 'low' ? 'text-forest' : tone === 'medium' ? 'text-amber' : 'text-brick'}`}>{Math.round(score * 100)}%</span></div> }
function PageHeader({ title, subtitle }) { return <div className="mb-7"><h1 className="font-serif text-3xl font-bold leading-tight text-navy md:text-4xl">{title}</h1><p className="mt-2 text-sm text-slate-500">{subtitle}</p></div> }
function FlaggedWorksList({ rows }) { if (!rows.length) return <div className="rounded-lg border border-divider bg-white p-8 text-center text-sm text-slate-400">No flagged works found for this record.</div>; return <div className="space-y-3">{rows.map((row) => <div className="rounded-lg border border-divider bg-white" key={row.work_id}><div className="flex flex-wrap items-center gap-4 p-4"><a href={`#risk/${row.work_id}`} className="font-bold text-navy hover:text-terracotta">{row.work_id}</a><span className="text-xs text-slate-500">{row.work_category || 'Work'}</span><RiskBar score={row.risk_score || 0} /><div className="flex flex-wrap gap-1">{(row.flags || []).map((flag) => <span className="rounded-full bg-brick/10 px-2 py-1 text-[10px] capitalize text-brick" key={flag}>{pretty(flag)}</span>)}</div><span className="ml-auto rounded-full border border-divider px-2 py-1 text-[10px] capitalize text-slate-500">{row.status || 'Under review'}</span></div><details className="border-t border-divider"><summary className="cursor-pointer list-none px-4 py-3 text-xs font-semibold text-terracotta">Why flagged <ChevronRight className="ml-1 inline" size={14} /></summary><p className="border-t border-divider bg-paper px-4 py-3 text-xs leading-5 text-slate-600">{row.explanation || 'No explanation was returned by the ML model.'}</p></details></div>)}</div> }
function RecordCards({ fields }) { return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{fields.map(([label, value, tone]) => <div className="rounded-lg border border-divider bg-white p-4" key={label}><span className="text-[10px] uppercase text-slate-400">{label}</span><b className={`mt-2 block ${tone === 'red' ? 'text-brick' : 'text-navy'}`}>{value}</b></div>)}</div> }
export function MPDetail({ name, dashboard, Frame }) { const { works, alerts, house } = dashboard; const mpWorks = (works.data || []).filter((item) => item.mp_name === name); const flagged = (alerts.data || []).filter((item) => item.mp_name === name).map((alert) => ({ ...mpWorks.find((work) => work.work_id === alert.work_id), ...alert })); const allocated = mpWorks.reduce((sum, item) => sum + (item.sanctioned_amount || 0), 0); return <Frame section="Browse MPs" subsection={name}><a href="#mps" className="mb-5 inline-flex items-center gap-2 text-xs font-bold text-terracotta"><ArrowLeft size={15} /> Back to Browse MPs</a><PageHeader title={name} subtitle={`Full MP fraud risk profile - ${house}`} /><RecordCards fields={[["Constituency", mpWorks[0]?.constituency || 'Not recorded'], ['State', mpWorks[0]?.state || 'Not recorded'], ['Allocated', crore(allocated)], ['Flagged works', flagged.length, 'red']]} /><div className="mt-6"><h2 className="mb-4 font-serif text-xl font-bold text-navy">Flagged works</h2><FlaggedWorksList rows={flagged} /></div></Frame> }
export function StateWorksDetail({ name, dashboard, Frame }) { const { works, alerts } = dashboard; const stateWorks = (works.data || []).filter((item) => item.state === name); const flagged = (alerts.data || []).filter((item) => item.state === name).map((alert) => ({ ...stateWorks.find((work) => work.work_id === alert.work_id), ...alert })); const allocated = stateWorks.reduce((sum, item) => sum + (item.sanctioned_amount || 0), 0); return <Frame section="Browse States" subsection={name}><a href="#states" className="mb-5 inline-flex items-center gap-2 text-xs font-bold text-terracotta"><ArrowLeft size={15} /> Back to All States</a><PageHeader title={name} subtitle="Full state fraud risk profile and flagged works" /><RecordCards fields={[["MPs", new Set(stateWorks.map((item) => item.mp_name)).size], ['Allocated', crore(allocated)], ['Total works', stateWorks.length], ['Flagged works', flagged.length, 'red']]} /><div className="mt-6"><h2 className="mb-4 font-serif text-xl font-bold text-navy">Flagged works</h2><FlaggedWorksList rows={flagged} /></div></Frame> }
